//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.12 at 08:04:01 PM TRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kps.nvi.gov.tr/2021/04/01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.tmo.tmokps.soap.api.kps;
