//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 05:40:44 PM EET 
//


package gov.tmo.tmokps.soap.api.yerlesim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfKimlikNoileAdresSorguKriteri complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfKimlikNoileAdresSorguKriteri"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="KimlikNoileAdresSorguKriteri" type="{http://kps.nvi.gov.tr/2011/01/01}KimlikNoileAdresSorguKriteri" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfKimlikNoileAdresSorguKriteri", namespace = "http://kps.nvi.gov.tr/2011/01/01", propOrder = {
    "kimlikNoileAdresSorguKriteri"
})
public class ArrayOfKimlikNoileAdresSorguKriteri {

    @XmlElement(name = "KimlikNoileAdresSorguKriteri", nillable = true)
    protected List<KimlikNoileAdresSorguKriteri> kimlikNoileAdresSorguKriteri;

    /**
     * Gets the value of the kimlikNoileAdresSorguKriteri property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kimlikNoileAdresSorguKriteri property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKimlikNoileAdresSorguKriteri().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KimlikNoileAdresSorguKriteri }
     * 
     * 
     */
    public List<KimlikNoileAdresSorguKriteri> getKimlikNoileAdresSorguKriteri() {
        if (kimlikNoileAdresSorguKriteri == null) {
            kimlikNoileAdresSorguKriteri = new ArrayList<KimlikNoileAdresSorguKriteri>();
        }
        return this.kimlikNoileAdresSorguKriteri;
    }

}
