//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 05:40:44 PM EET 
//


package gov.tmo.tmokps.soap.api.yerlesim;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KimlikNoileKisiAdresBilgisi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KimlikNoileKisiAdresBilgisi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AcikAdres" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AdresNo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="AdresTip" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="BeldeAdresi" type="{http://kps.nvi.gov.tr/2018/04/01}KimlikNoileBeldeAdresi" minOccurs="0"/&gt;
 *         &lt;element name="BeyanTarihi" type="{http://kps.nvi.gov.tr/2011/01/01}TarihBilgisi" minOccurs="0"/&gt;
 *         &lt;element name="BeyandaBulunanKimlikNo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="HataBilgisi" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="IlIlceMerkezAdresi" type="{http://kps.nvi.gov.tr/2018/04/01}KimlikNoileIlIlceMerkezi" minOccurs="0"/&gt;
 *         &lt;element name="KoyAdresi" type="{http://kps.nvi.gov.tr/2018/04/01}KimlikNoileKoyAdresi" minOccurs="0"/&gt;
 *         &lt;element name="TasinmaNeden" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="TasinmaNedenAciklama" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TasinmaTarihi" type="{http://kps.nvi.gov.tr/2011/01/01}TarihBilgisi" minOccurs="0"/&gt;
 *         &lt;element name="TescilTarihi" type="{http://kps.nvi.gov.tr/2011/01/01}TarihBilgisi" minOccurs="0"/&gt;
 *         &lt;element name="YurtDisiAdresi" type="{http://kps.nvi.gov.tr/2011/01/01}KimlikNoileYurtDisiAdresi" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KimlikNoileKisiAdresBilgisi", propOrder = {
    "acikAdres",
    "adresNo",
    "adresTip",
    "beldeAdresi",
    "beyanTarihi",
    "beyandaBulunanKimlikNo",
    "hataBilgisi",
    "ilIlceMerkezAdresi",
    "koyAdresi",
    "tasinmaNeden",
    "tasinmaNedenAciklama",
    "tasinmaTarihi",
    "tescilTarihi",
    "yurtDisiAdresi"
})
public class KimlikNoileKisiAdresBilgisi {

    @XmlElementRef(name = "AcikAdres", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> acikAdres;
    @XmlElementRef(name = "AdresNo", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> adresNo;
    @XmlElementRef(name = "AdresTip", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> adresTip;
    @XmlElementRef(name = "BeldeAdresi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<KimlikNoileBeldeAdresi> beldeAdresi;
    @XmlElementRef(name = "BeyanTarihi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<TarihBilgisi> beyanTarihi;
    @XmlElementRef(name = "BeyandaBulunanKimlikNo", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> beyandaBulunanKimlikNo;
    @XmlElementRef(name = "HataBilgisi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> hataBilgisi;
    @XmlElementRef(name = "IlIlceMerkezAdresi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<KimlikNoileIlIlceMerkezi> ilIlceMerkezAdresi;
    @XmlElementRef(name = "KoyAdresi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<KimlikNoileKoyAdresi> koyAdresi;
    @XmlElementRef(name = "TasinmaNeden", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> tasinmaNeden;
    @XmlElementRef(name = "TasinmaNedenAciklama", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tasinmaNedenAciklama;
    @XmlElementRef(name = "TasinmaTarihi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<TarihBilgisi> tasinmaTarihi;
    @XmlElementRef(name = "TescilTarihi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<TarihBilgisi> tescilTarihi;
    @XmlElementRef(name = "YurtDisiAdresi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<KimlikNoileYurtDisiAdresi> yurtDisiAdresi;

    /**
     * Gets the value of the acikAdres property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAcikAdres() {
        return acikAdres;
    }

    /**
     * Sets the value of the acikAdres property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAcikAdres(JAXBElement<String> value) {
        this.acikAdres = value;
    }

    /**
     * Gets the value of the adresNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getAdresNo() {
        return adresNo;
    }

    /**
     * Sets the value of the adresNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setAdresNo(JAXBElement<Long> value) {
        this.adresNo = value;
    }

    /**
     * Gets the value of the adresTip property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getAdresTip() {
        return adresTip;
    }

    /**
     * Sets the value of the adresTip property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setAdresTip(JAXBElement<Parametre> value) {
        this.adresTip = value;
    }

    /**
     * Gets the value of the beldeAdresi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link KimlikNoileBeldeAdresi }{@code >}
     *     
     */
    public JAXBElement<KimlikNoileBeldeAdresi> getBeldeAdresi() {
        return beldeAdresi;
    }

    /**
     * Sets the value of the beldeAdresi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link KimlikNoileBeldeAdresi }{@code >}
     *     
     */
    public void setBeldeAdresi(JAXBElement<KimlikNoileBeldeAdresi> value) {
        this.beldeAdresi = value;
    }

    /**
     * Gets the value of the beyanTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TarihBilgisi }{@code >}
     *     
     */
    public JAXBElement<TarihBilgisi> getBeyanTarihi() {
        return beyanTarihi;
    }

    /**
     * Sets the value of the beyanTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TarihBilgisi }{@code >}
     *     
     */
    public void setBeyanTarihi(JAXBElement<TarihBilgisi> value) {
        this.beyanTarihi = value;
    }

    /**
     * Gets the value of the beyandaBulunanKimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getBeyandaBulunanKimlikNo() {
        return beyandaBulunanKimlikNo;
    }

    /**
     * Sets the value of the beyandaBulunanKimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setBeyandaBulunanKimlikNo(JAXBElement<Long> value) {
        this.beyandaBulunanKimlikNo = value;
    }

    /**
     * Gets the value of the hataBilgisi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getHataBilgisi() {
        return hataBilgisi;
    }

    /**
     * Sets the value of the hataBilgisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setHataBilgisi(JAXBElement<Parametre> value) {
        this.hataBilgisi = value;
    }

    /**
     * Gets the value of the ilIlceMerkezAdresi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link KimlikNoileIlIlceMerkezi }{@code >}
     *     
     */
    public JAXBElement<KimlikNoileIlIlceMerkezi> getIlIlceMerkezAdresi() {
        return ilIlceMerkezAdresi;
    }

    /**
     * Sets the value of the ilIlceMerkezAdresi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link KimlikNoileIlIlceMerkezi }{@code >}
     *     
     */
    public void setIlIlceMerkezAdresi(JAXBElement<KimlikNoileIlIlceMerkezi> value) {
        this.ilIlceMerkezAdresi = value;
    }

    /**
     * Gets the value of the koyAdresi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link KimlikNoileKoyAdresi }{@code >}
     *     
     */
    public JAXBElement<KimlikNoileKoyAdresi> getKoyAdresi() {
        return koyAdresi;
    }

    /**
     * Sets the value of the koyAdresi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link KimlikNoileKoyAdresi }{@code >}
     *     
     */
    public void setKoyAdresi(JAXBElement<KimlikNoileKoyAdresi> value) {
        this.koyAdresi = value;
    }

    /**
     * Gets the value of the tasinmaNeden property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getTasinmaNeden() {
        return tasinmaNeden;
    }

    /**
     * Sets the value of the tasinmaNeden property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setTasinmaNeden(JAXBElement<Parametre> value) {
        this.tasinmaNeden = value;
    }

    /**
     * Gets the value of the tasinmaNedenAciklama property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTasinmaNedenAciklama() {
        return tasinmaNedenAciklama;
    }

    /**
     * Sets the value of the tasinmaNedenAciklama property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTasinmaNedenAciklama(JAXBElement<String> value) {
        this.tasinmaNedenAciklama = value;
    }

    /**
     * Gets the value of the tasinmaTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TarihBilgisi }{@code >}
     *     
     */
    public JAXBElement<TarihBilgisi> getTasinmaTarihi() {
        return tasinmaTarihi;
    }

    /**
     * Sets the value of the tasinmaTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TarihBilgisi }{@code >}
     *     
     */
    public void setTasinmaTarihi(JAXBElement<TarihBilgisi> value) {
        this.tasinmaTarihi = value;
    }

    /**
     * Gets the value of the tescilTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TarihBilgisi }{@code >}
     *     
     */
    public JAXBElement<TarihBilgisi> getTescilTarihi() {
        return tescilTarihi;
    }

    /**
     * Sets the value of the tescilTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TarihBilgisi }{@code >}
     *     
     */
    public void setTescilTarihi(JAXBElement<TarihBilgisi> value) {
        this.tescilTarihi = value;
    }

    /**
     * Gets the value of the yurtDisiAdresi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link KimlikNoileYurtDisiAdresi }{@code >}
     *     
     */
    public JAXBElement<KimlikNoileYurtDisiAdresi> getYurtDisiAdresi() {
        return yurtDisiAdresi;
    }

    /**
     * Sets the value of the yurtDisiAdresi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link KimlikNoileYurtDisiAdresi }{@code >}
     *     
     */
    public void setYurtDisiAdresi(JAXBElement<KimlikNoileYurtDisiAdresi> value) {
        this.yurtDisiAdresi = value;
    }

}
