//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 05:40:44 PM EET 
//


package gov.tmo.tmokps.soap.api.yerlesim;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KimlikNoileIlIlceMerkezi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KimlikNoileIlIlceMerkezi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BagimsizBolumDurum" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="BagimsizBolumTipi" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="BinaAda" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BinaBlokAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BinaDurum" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="BinaKodu" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="BinaNo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="BinaNumaratajTipi" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="BinaPafta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BinaParsel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BinaSiteAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BinaYapiTipi" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="Csbm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CsbmKodu" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="DisKapiNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HataBilgisi" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="IcKapiNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Il" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IlKodu" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Ilce" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IlceKodu" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="KatNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Mahalle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MahalleKodu" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="TapuBagimsizBolumNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="YapiKullanimAmac" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="YolAltiKatSayisi" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="YolUstuKatSayisi" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KimlikNoileIlIlceMerkezi", propOrder = {
    "bagimsizBolumDurum",
    "bagimsizBolumTipi",
    "binaAda",
    "binaBlokAdi",
    "binaDurum",
    "binaKodu",
    "binaNo",
    "binaNumaratajTipi",
    "binaPafta",
    "binaParsel",
    "binaSiteAdi",
    "binaYapiTipi",
    "csbm",
    "csbmKodu",
    "disKapiNo",
    "hataBilgisi",
    "icKapiNo",
    "il",
    "ilKodu",
    "ilce",
    "ilceKodu",
    "katNo",
    "mahalle",
    "mahalleKodu",
    "tapuBagimsizBolumNo",
    "yapiKullanimAmac",
    "yolAltiKatSayisi",
    "yolUstuKatSayisi"
})
public class KimlikNoileIlIlceMerkezi {

    @XmlElementRef(name = "BagimsizBolumDurum", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> bagimsizBolumDurum;
    @XmlElementRef(name = "BagimsizBolumTipi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> bagimsizBolumTipi;
    @XmlElementRef(name = "BinaAda", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> binaAda;
    @XmlElementRef(name = "BinaBlokAdi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> binaBlokAdi;
    @XmlElementRef(name = "BinaDurum", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> binaDurum;
    @XmlElementRef(name = "BinaKodu", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> binaKodu;
    @XmlElementRef(name = "BinaNo", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> binaNo;
    @XmlElementRef(name = "BinaNumaratajTipi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> binaNumaratajTipi;
    @XmlElementRef(name = "BinaPafta", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> binaPafta;
    @XmlElementRef(name = "BinaParsel", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> binaParsel;
    @XmlElementRef(name = "BinaSiteAdi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> binaSiteAdi;
    @XmlElementRef(name = "BinaYapiTipi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> binaYapiTipi;
    @XmlElementRef(name = "Csbm", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> csbm;
    @XmlElementRef(name = "CsbmKodu", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> csbmKodu;
    @XmlElementRef(name = "DisKapiNo", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> disKapiNo;
    @XmlElementRef(name = "HataBilgisi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> hataBilgisi;
    @XmlElementRef(name = "IcKapiNo", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> icKapiNo;
    @XmlElementRef(name = "Il", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> il;
    @XmlElementRef(name = "IlKodu", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> ilKodu;
    @XmlElementRef(name = "Ilce", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ilce;
    @XmlElementRef(name = "IlceKodu", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> ilceKodu;
    @XmlElementRef(name = "KatNo", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> katNo;
    @XmlElementRef(name = "Mahalle", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> mahalle;
    @XmlElementRef(name = "MahalleKodu", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> mahalleKodu;
    @XmlElementRef(name = "TapuBagimsizBolumNo", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tapuBagimsizBolumNo;
    @XmlElementRef(name = "YapiKullanimAmac", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> yapiKullanimAmac;
    @XmlElementRef(name = "YolAltiKatSayisi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> yolAltiKatSayisi;
    @XmlElementRef(name = "YolUstuKatSayisi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> yolUstuKatSayisi;

    /**
     * Gets the value of the bagimsizBolumDurum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getBagimsizBolumDurum() {
        return bagimsizBolumDurum;
    }

    /**
     * Sets the value of the bagimsizBolumDurum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setBagimsizBolumDurum(JAXBElement<Parametre> value) {
        this.bagimsizBolumDurum = value;
    }

    /**
     * Gets the value of the bagimsizBolumTipi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getBagimsizBolumTipi() {
        return bagimsizBolumTipi;
    }

    /**
     * Sets the value of the bagimsizBolumTipi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setBagimsizBolumTipi(JAXBElement<Parametre> value) {
        this.bagimsizBolumTipi = value;
    }

    /**
     * Gets the value of the binaAda property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBinaAda() {
        return binaAda;
    }

    /**
     * Sets the value of the binaAda property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBinaAda(JAXBElement<String> value) {
        this.binaAda = value;
    }

    /**
     * Gets the value of the binaBlokAdi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBinaBlokAdi() {
        return binaBlokAdi;
    }

    /**
     * Sets the value of the binaBlokAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBinaBlokAdi(JAXBElement<String> value) {
        this.binaBlokAdi = value;
    }

    /**
     * Gets the value of the binaDurum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getBinaDurum() {
        return binaDurum;
    }

    /**
     * Sets the value of the binaDurum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setBinaDurum(JAXBElement<Parametre> value) {
        this.binaDurum = value;
    }

    /**
     * Gets the value of the binaKodu property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getBinaKodu() {
        return binaKodu;
    }

    /**
     * Sets the value of the binaKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setBinaKodu(JAXBElement<Long> value) {
        this.binaKodu = value;
    }

    /**
     * Gets the value of the binaNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getBinaNo() {
        return binaNo;
    }

    /**
     * Sets the value of the binaNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setBinaNo(JAXBElement<Integer> value) {
        this.binaNo = value;
    }

    /**
     * Gets the value of the binaNumaratajTipi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getBinaNumaratajTipi() {
        return binaNumaratajTipi;
    }

    /**
     * Sets the value of the binaNumaratajTipi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setBinaNumaratajTipi(JAXBElement<Parametre> value) {
        this.binaNumaratajTipi = value;
    }

    /**
     * Gets the value of the binaPafta property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBinaPafta() {
        return binaPafta;
    }

    /**
     * Sets the value of the binaPafta property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBinaPafta(JAXBElement<String> value) {
        this.binaPafta = value;
    }

    /**
     * Gets the value of the binaParsel property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBinaParsel() {
        return binaParsel;
    }

    /**
     * Sets the value of the binaParsel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBinaParsel(JAXBElement<String> value) {
        this.binaParsel = value;
    }

    /**
     * Gets the value of the binaSiteAdi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBinaSiteAdi() {
        return binaSiteAdi;
    }

    /**
     * Sets the value of the binaSiteAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBinaSiteAdi(JAXBElement<String> value) {
        this.binaSiteAdi = value;
    }

    /**
     * Gets the value of the binaYapiTipi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getBinaYapiTipi() {
        return binaYapiTipi;
    }

    /**
     * Sets the value of the binaYapiTipi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setBinaYapiTipi(JAXBElement<Parametre> value) {
        this.binaYapiTipi = value;
    }

    /**
     * Gets the value of the csbm property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCsbm() {
        return csbm;
    }

    /**
     * Sets the value of the csbm property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCsbm(JAXBElement<String> value) {
        this.csbm = value;
    }

    /**
     * Gets the value of the csbmKodu property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getCsbmKodu() {
        return csbmKodu;
    }

    /**
     * Sets the value of the csbmKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setCsbmKodu(JAXBElement<Integer> value) {
        this.csbmKodu = value;
    }

    /**
     * Gets the value of the disKapiNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDisKapiNo() {
        return disKapiNo;
    }

    /**
     * Sets the value of the disKapiNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDisKapiNo(JAXBElement<String> value) {
        this.disKapiNo = value;
    }

    /**
     * Gets the value of the hataBilgisi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getHataBilgisi() {
        return hataBilgisi;
    }

    /**
     * Sets the value of the hataBilgisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setHataBilgisi(JAXBElement<Parametre> value) {
        this.hataBilgisi = value;
    }

    /**
     * Gets the value of the icKapiNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIcKapiNo() {
        return icKapiNo;
    }

    /**
     * Sets the value of the icKapiNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIcKapiNo(JAXBElement<String> value) {
        this.icKapiNo = value;
    }

    /**
     * Gets the value of the il property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIl() {
        return il;
    }

    /**
     * Sets the value of the il property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIl(JAXBElement<String> value) {
        this.il = value;
    }

    /**
     * Gets the value of the ilKodu property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getIlKodu() {
        return ilKodu;
    }

    /**
     * Sets the value of the ilKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setIlKodu(JAXBElement<Integer> value) {
        this.ilKodu = value;
    }

    /**
     * Gets the value of the ilce property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIlce() {
        return ilce;
    }

    /**
     * Sets the value of the ilce property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIlce(JAXBElement<String> value) {
        this.ilce = value;
    }

    /**
     * Gets the value of the ilceKodu property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getIlceKodu() {
        return ilceKodu;
    }

    /**
     * Sets the value of the ilceKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setIlceKodu(JAXBElement<Integer> value) {
        this.ilceKodu = value;
    }

    /**
     * Gets the value of the katNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getKatNo() {
        return katNo;
    }

    /**
     * Sets the value of the katNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setKatNo(JAXBElement<String> value) {
        this.katNo = value;
    }

    /**
     * Gets the value of the mahalle property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMahalle() {
        return mahalle;
    }

    /**
     * Sets the value of the mahalle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMahalle(JAXBElement<String> value) {
        this.mahalle = value;
    }

    /**
     * Gets the value of the mahalleKodu property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getMahalleKodu() {
        return mahalleKodu;
    }

    /**
     * Sets the value of the mahalleKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setMahalleKodu(JAXBElement<Integer> value) {
        this.mahalleKodu = value;
    }

    /**
     * Gets the value of the tapuBagimsizBolumNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTapuBagimsizBolumNo() {
        return tapuBagimsizBolumNo;
    }

    /**
     * Sets the value of the tapuBagimsizBolumNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTapuBagimsizBolumNo(JAXBElement<String> value) {
        this.tapuBagimsizBolumNo = value;
    }

    /**
     * Gets the value of the yapiKullanimAmac property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getYapiKullanimAmac() {
        return yapiKullanimAmac;
    }

    /**
     * Sets the value of the yapiKullanimAmac property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setYapiKullanimAmac(JAXBElement<Parametre> value) {
        this.yapiKullanimAmac = value;
    }

    /**
     * Gets the value of the yolAltiKatSayisi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getYolAltiKatSayisi() {
        return yolAltiKatSayisi;
    }

    /**
     * Sets the value of the yolAltiKatSayisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setYolAltiKatSayisi(JAXBElement<Integer> value) {
        this.yolAltiKatSayisi = value;
    }

    /**
     * Gets the value of the yolUstuKatSayisi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getYolUstuKatSayisi() {
        return yolUstuKatSayisi;
    }

    /**
     * Sets the value of the yolUstuKatSayisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setYolUstuKatSayisi(JAXBElement<Integer> value) {
        this.yolUstuKatSayisi = value;
    }

}
