//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 05:40:44 PM EET 
//


package gov.tmo.tmokps.soap.api.yerlesim;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for KimlikNoileYurtDisiAdresi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KimlikNoileYurtDisiAdresi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DisTemsDuzeltmeBeyanTarih" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="DisTemsDuzeltmeKararTarih" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="DisTemsDuzeltmeNeden" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="DisTemsilcilik" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="HataBilgisi" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *         &lt;element name="YabanciAdres" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="YabanciSehir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="YabanciUlke" type="{http://kps.nvi.gov.tr/2011/01/01}Parametre" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KimlikNoileYurtDisiAdresi", namespace = "http://kps.nvi.gov.tr/2011/01/01", propOrder = {
    "disTemsDuzeltmeBeyanTarih",
    "disTemsDuzeltmeKararTarih",
    "disTemsDuzeltmeNeden",
    "disTemsilcilik",
    "hataBilgisi",
    "yabanciAdres",
    "yabanciSehir",
    "yabanciUlke"
})
public class KimlikNoileYurtDisiAdresi {

    @XmlElementRef(name = "DisTemsDuzeltmeBeyanTarih", namespace = "http://kps.nvi.gov.tr/2011/01/01", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> disTemsDuzeltmeBeyanTarih;
    @XmlElementRef(name = "DisTemsDuzeltmeKararTarih", namespace = "http://kps.nvi.gov.tr/2011/01/01", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> disTemsDuzeltmeKararTarih;
    @XmlElementRef(name = "DisTemsDuzeltmeNeden", namespace = "http://kps.nvi.gov.tr/2011/01/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> disTemsDuzeltmeNeden;
    @XmlElementRef(name = "DisTemsilcilik", namespace = "http://kps.nvi.gov.tr/2011/01/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> disTemsilcilik;
    @XmlElementRef(name = "HataBilgisi", namespace = "http://kps.nvi.gov.tr/2011/01/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> hataBilgisi;
    @XmlElementRef(name = "YabanciAdres", namespace = "http://kps.nvi.gov.tr/2011/01/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> yabanciAdres;
    @XmlElementRef(name = "YabanciSehir", namespace = "http://kps.nvi.gov.tr/2011/01/01", type = JAXBElement.class, required = false)
    protected JAXBElement<String> yabanciSehir;
    @XmlElementRef(name = "YabanciUlke", namespace = "http://kps.nvi.gov.tr/2011/01/01", type = JAXBElement.class, required = false)
    protected JAXBElement<Parametre> yabanciUlke;

    /**
     * Gets the value of the disTemsDuzeltmeBeyanTarih property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getDisTemsDuzeltmeBeyanTarih() {
        return disTemsDuzeltmeBeyanTarih;
    }

    /**
     * Sets the value of the disTemsDuzeltmeBeyanTarih property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDisTemsDuzeltmeBeyanTarih(JAXBElement<XMLGregorianCalendar> value) {
        this.disTemsDuzeltmeBeyanTarih = value;
    }

    /**
     * Gets the value of the disTemsDuzeltmeKararTarih property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getDisTemsDuzeltmeKararTarih() {
        return disTemsDuzeltmeKararTarih;
    }

    /**
     * Sets the value of the disTemsDuzeltmeKararTarih property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDisTemsDuzeltmeKararTarih(JAXBElement<XMLGregorianCalendar> value) {
        this.disTemsDuzeltmeKararTarih = value;
    }

    /**
     * Gets the value of the disTemsDuzeltmeNeden property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getDisTemsDuzeltmeNeden() {
        return disTemsDuzeltmeNeden;
    }

    /**
     * Sets the value of the disTemsDuzeltmeNeden property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setDisTemsDuzeltmeNeden(JAXBElement<Parametre> value) {
        this.disTemsDuzeltmeNeden = value;
    }

    /**
     * Gets the value of the disTemsilcilik property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getDisTemsilcilik() {
        return disTemsilcilik;
    }

    /**
     * Sets the value of the disTemsilcilik property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setDisTemsilcilik(JAXBElement<Parametre> value) {
        this.disTemsilcilik = value;
    }

    /**
     * Gets the value of the hataBilgisi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getHataBilgisi() {
        return hataBilgisi;
    }

    /**
     * Sets the value of the hataBilgisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setHataBilgisi(JAXBElement<Parametre> value) {
        this.hataBilgisi = value;
    }

    /**
     * Gets the value of the yabanciAdres property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getYabanciAdres() {
        return yabanciAdres;
    }

    /**
     * Sets the value of the yabanciAdres property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setYabanciAdres(JAXBElement<String> value) {
        this.yabanciAdres = value;
    }

    /**
     * Gets the value of the yabanciSehir property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getYabanciSehir() {
        return yabanciSehir;
    }

    /**
     * Sets the value of the yabanciSehir property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setYabanciSehir(JAXBElement<String> value) {
        this.yabanciSehir = value;
    }

    /**
     * Gets the value of the yabanciUlke property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public JAXBElement<Parametre> getYabanciUlke() {
        return yabanciUlke;
    }

    /**
     * Sets the value of the yabanciUlke property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Parametre }{@code >}
     *     
     */
    public void setYabanciUlke(JAXBElement<Parametre> value) {
        this.yabanciUlke = value;
    }

}
