//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 05:40:44 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kps.nvi.gov.tr/2018/04/01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.tmo.tmokps.soap.api.yerlesim;
