//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 05:40:44 PM EET 
//


package gov.tmo.tmokps.soap.api.yerlesim;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kriterListesi" type="{http://kps.nvi.gov.tr/2011/01/01}ArrayOfKimlikNoileAdresSorguKriteri" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kriterListesi"
})
@XmlRootElement(name = "Sorgula")
public class Sorgula {

    @XmlElementRef(name = "kriterListesi", namespace = "http://kps.nvi.gov.tr/2018/04/01", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfKimlikNoileAdresSorguKriteri> kriterListesi;

    /**
     * Gets the value of the kriterListesi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfKimlikNoileAdresSorguKriteri }{@code >}
     *     
     */
    public JAXBElement<ArrayOfKimlikNoileAdresSorguKriteri> getKriterListesi() {
        return kriterListesi;
    }

    /**
     * Sets the value of the kriterListesi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfKimlikNoileAdresSorguKriteri }{@code >}
     *     
     */
    public void setKriterListesi(JAXBElement<ArrayOfKimlikNoileAdresSorguKriteri> value) {
        this.kriterListesi = value;
    }

}
